import FWCore.ParameterSet.Config as cms

maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )
readFiles = cms.untracked.vstring()
secFiles = cms.untracked.vstring() 
source = cms.Source ("PoolSource",fileNames = readFiles, secondaryFileNames = secFiles)
readFiles.extend( [
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_10_1_bIY.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_11_1_Zla.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_12_1_hwZ.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_13_1_j65.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_14_1_UqG.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_15_1_id1.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_16_1_JEj.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_17_1_I1k.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_18_1_pvt.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_19_1_1dZ.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_1_1_KQU.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_20_1_BOO.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_21_1_DZl.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_22_1_Wox.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_23_1_lnO.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_24_1_U6S.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_25_1_BYy.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_26_1_XRX.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_27_1_fPC.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_28_1_CoR.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_29_1_HCB.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_2_1_KDt.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_30_1_DLv.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_31_1_fPE.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_32_1_V1I.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_33_1_8Gx.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_34_1_6qT.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_35_1_86k.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_36_1_Nhg.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_37_1_dBL.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_38_1_a8b.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_39_1_kwY.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_3_1_VPp.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_40_1_AR9.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_41_1_0yX.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_42_1_Qkv.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_43_1_CIW.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_44_1_1tG.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_45_1_g8l.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_46_1_uvO.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_48_1_d2Y.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_49_1_G1a.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_4_1_GtK.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_50_1_nOs.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_51_1_9x6.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_5_1_Cm9.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_6_1_pg4.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_7_1_ACP.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_8_1_Qp1.root",
"dcap:///pnfs/cms/WAX/resilient/crsilk/StopSearches/QCD_Pt-15to3000_TuneZ2_Flat_7TeV_pythia6/ttbsm_ultraslim_9_1_9Zd.root"
	])
