import FWCore.ParameterSet.Config as cms

maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )
readFiles = cms.untracked.vstring()
secFiles = cms.untracked.vstring() 
source = cms.Source ("PoolSource",fileNames = readFiles, secondaryFileNames = secFiles)
readFiles.extend( [
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_10_1_lPI.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_11_1_ZW2.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_1_1_dB0.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_12_1_kTN.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_13_1_L8v.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_14_1_Rak.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_15_1_I9a.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_16_1_9OI.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_17_1_pxw.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_18_1_71l.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_19_1_Snd.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_20_1_Cdo.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_21_1_Lai.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_22_1_SzO.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_23_1_Zx6.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_24_1_KYF.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_25_1_eci.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_26_1_jjF.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_27_1_Mn3.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_28_1_PKd.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_29_1_8PL.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_30_1_IWL.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_31_1_6SN.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_3_1_ymV.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_32_1_rFL.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_33_1_841.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_34_1_SOE.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_35_1_Ec1.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_36_1_qHQ.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_37_1_kTE.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_38_1_l7B.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_39_1_TYK.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_40_1_8m2.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_41_1_xPY.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_4_1_2xB.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_42_1_uUx.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_43_1_tZH.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_44_1_3kH.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_45_1_Aik.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_46_1_DPe.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_47_1_lEG.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_48_1_Gt2.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_49_1_DJB.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_50_1_VNd.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_51_1_xwv.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_5_1_SWw.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_6_1_xdv.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_7_1_7z8.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_8_1_sSy.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_9_1_2Nb.root"
	])
