import FWCore.ParameterSet.Config as cms

maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )
readFiles = cms.untracked.vstring()
secFiles = cms.untracked.vstring() 
source = cms.Source ("PoolSource",fileNames = readFiles, secondaryFileNames = secFiles)
readFiles.extend( [
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_22_1_vWI.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_33_1_OWR.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_50_1_68H.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_26_1_MPa.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_23_1_Wnw.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_1_1_AHI.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_32_1_qwh.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_20_1_0K5.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_9_1_3Pe.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_15_1_oNf.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_44_1_jHl.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_10_1_39S.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_51_1_Dsf.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_48_1_02h.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_5_1_Ycw.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_39_1_SqT.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_37_1_lVo.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_16_1_Eg0.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_11_1_V6h.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_21_1_kWL.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_6_1_PvQ.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_41_1_sZE.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_43_1_Swq.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_8_1_Pos.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_4_1_iyI.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_47_1_pHQ.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_7_1_MSZ.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_36_1_8Iu.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_3_1_Obt.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_35_1_Ksq.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_40_1_tWL.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_29_1_msX.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_2_1_EkG.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_27_1_nYA.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_28_1_mhg.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_31_1_BDa.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_12_1_iLx.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_14_1_AP3.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_18_1_j70.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_17_1_Dmp.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_24_1_7g4.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_19_1_S5H.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_38_1_Dz2.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_13_1_7AZ.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_45_1_gSG.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_49_1_zxT.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_42_1_HOG.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_25_1_KOv.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_46_1_EPP.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_34_1_Q7L.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_30_1_Icn.root",
])