import FWCore.ParameterSet.Config as cms

maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )
readFiles = cms.untracked.vstring()
secFiles = cms.untracked.vstring() 
source = cms.Source ("PoolSource",fileNames = readFiles, secondaryFileNames = secFiles)
readFiles.extend( [
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_10_1_fZN.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_11_1_dAS.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_1_1_H2q.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_12_1_iZY.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_13_1_Rjx.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_14_1_NPE.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_15_1_hrl.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_16_1_Ctx.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_17_1_wBY.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_18_1_r9g.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_19_1_Hfw.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_20_1_XRR.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_21_1_6B4.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_2_1_m5u.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_22_1_NOY.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_23_1_gJ2.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_24_1_eZU.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_26_1_QwG.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_27_1_lSU.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_28_1_OUP.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_29_1_3nH.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_30_1_A9r.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_31_1_fuh.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_3_1_MdR.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_32_1_BdW.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_33_1_fwX.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_34_1_LPu.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_35_1_tvs.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_36_1_8SX.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_37_1_wb2.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_38_1_yQE.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_39_1_eP0.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_40_1_HoC.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_41_1_dhx.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_4_1_U7k.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_42_1_i7R.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_43_1_59m.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_44_1_eou.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_45_1_57j.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_46_1_7Xj.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_47_1_Rj2.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_48_1_ERq.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_49_1_Ycz.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_50_1_Axq.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_51_1_AGS.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_5_1_vKW.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_6_1_4Vg.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_7_1_tVy.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_8_1_Seb.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/TTJets_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_9_1_zGg.root"
	])
