import FWCore.ParameterSet.Config as cms

maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )
readFiles = cms.untracked.vstring()
secFiles = cms.untracked.vstring()
source = cms.Source ("PoolSource",fileNames = readFiles, secondaryFileNames = secFiles)
readFiles.extend( [
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_10_1_QnA.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_11_1_h21.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_12_1_wQf.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_13_1_pOu.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_14_1_kRr.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_15_1_fbo.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_16_1_McC.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_17_1_9oB.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_18_1_GjK.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_19_1_KNa.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_1_1_OcN.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_20_1_JaA.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_21_1_NOr.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_22_1_WTm.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_23_1_EqR.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_24_1_qJP.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_25_1_B1O.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_26_1_2a4.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_27_1_HxQ.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_28_1_mLe.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_29_1_Hdf.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_2_1_SSC.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_30_1_YuV.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_31_1_thf.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_32_1_Fl9.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_33_1_xxB.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_34_1_1et.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_35_1_JhD.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_36_1_iOM.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_37_1_MgJ.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_38_1_cqC.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_39_1_aKx.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_3_1_zaO.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_40_1_76H.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_41_1_Rz8.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_42_1_ef0.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_43_1_QPS.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_44_1_nP2.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_45_1_ekX.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_46_1_T1M.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_47_1_OcQ.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_48_1_xLS.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_49_1_bai.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_4_1_iPv.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_50_1_Ntv.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_51_1_Y4J.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_5_1_cWY.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_6_1_ySv.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_7_1_G6y.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_8_1_I2M.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_9_1_Bub.root"
	])
