import FWCore.ParameterSet.Config as cms

maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )
readFiles = cms.untracked.vstring()
secFiles = cms.untracked.vstring() 
source = cms.Source ("PoolSource",fileNames = readFiles, secondaryFileNames = secFiles)
readFiles.extend( [
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_4_1_OEV.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_11_1_fkn.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_50_1_Ff1.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_48_1_f35.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_38_1_JYB.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_32_1_JqV.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_22_1_aiH.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_33_1_qG1.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_40_1_OEt.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_45_1_BmD.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_25_1_5Z5.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_43_1_UzX.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_41_1_iYV.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_27_1_fdV.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_13_1_7Of.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_18_1_hEV.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_8_1_VSN.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_21_1_Gbf.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_15_1_73n.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_2_1_c1J.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_29_1_kgn.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_37_1_bNc.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_20_1_etX.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_17_1_0IK.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_36_1_E8Q.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_9_1_4AU.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_28_1_BSX.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_7_1_k9C.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_3_1_dcz.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_14_1_xUq.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_51_1_pUD.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_47_1_G68.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_12_1_eAP.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_1_1_Izn.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_44_1_acv.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_49_1_CRG.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_10_1_pzs.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_5_1_m9A.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_26_1_EYL.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_42_1_1hJ.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_39_1_hA3.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_35_1_jjE.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_23_1_Fex.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_16_1_2Wn.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_31_1_zai.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_34_1_83w.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_30_1_ttw.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_46_1_0Xx.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_6_1_0Jv.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_24_1_Pmb.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/ttbsm_ultraslim_19_1_6tR.root",
])