import FWCore.ParameterSet.Config as cms

maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )
readFiles = cms.untracked.vstring()
secFiles = cms.untracked.vstring() 
source = cms.Source ("PoolSource",fileNames = readFiles, secondaryFileNames = secFiles)
readFiles.extend( [
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_10_1_s9o.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_11_1_034.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_1_1_ZAQ.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_12_1_rA8.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_13_1_pNp.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_14_1_Fbq.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_15_1_9pE.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_16_1_lRL.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_17_1_ssr.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_18_1_OwH.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_19_1_tt2.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_20_1_mkr.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_21_1_mib.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_2_1_iGS.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_22_1_EsQ.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_23_1_Ntn.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_24_1_pEY.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_25_1_2ir.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_26_1_Yde.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_27_1_kBZ.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_28_1_7pc.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_29_1_AUN.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_30_1_M46.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_31_1_xJp.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_3_1_met.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_32_1_MTW.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_33_1_9Nh.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_34_1_Rom.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_35_1_Bso.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_36_1_gWW.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_37_1_JIC.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_38_1_GOF.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_39_1_ArG.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_40_1_UTZ.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_41_1_Gln.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_4_1_rGP.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_42_1_Q4r.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_43_1_6Gz.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_44_1_FaK.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_45_1_W2g.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_46_1_K39.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_47_1_7oi.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_48_1_ql9.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_49_1_qnm.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_50_1_igQ.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_51_1_0zf.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_5_1_MyI.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_6_1_7zC.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_7_1_Wh8.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_8_1_6tP.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_200_HT_inf_7TeV-madgraph/ttbsm_ultraslim_9_1_NC3.root"

])
