import FWCore.ParameterSet.Config as cms

maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )
readFiles = cms.untracked.vstring()
secFiles = cms.untracked.vstring() 
source = cms.Source ("PoolSource",fileNames = readFiles, secondaryFileNames = secFiles)
readFiles.extend( [
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_22_1_ekA.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_35_1_AF9.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_11_1_Nu3.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_12_1_WYc.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_7_1_KZ5.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_39_1_6kU.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_25_1_FmJ.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_3_1_nuz.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_24_1_leN.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_49_1_ZNv.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_26_1_1Bl.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_2_1_m8J.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_38_1_OTq.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_40_1_Ims.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_47_1_oI0.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_20_1_oey.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_36_1_xcw.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_30_1_hZE.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_43_1_1CM.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_17_1_oGl.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_18_1_0pX.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_51_1_Abs.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_41_1_9ol.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_14_1_tj6.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_27_1_nm2.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_16_1_Kvv.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_48_1_IgR.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_6_1_NUB.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_23_1_xXI.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_15_1_Q3C.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_32_1_vDm.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_45_1_DaK.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_1_1_sGi.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_42_1_rox.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_13_1_HOG.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_4_1_hgH.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_28_1_W6H.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_50_1_nLB.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_10_1_M0g.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_37_1_G5J.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_21_1_yC8.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_5_1_xPH.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_29_1_oLm.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_34_1_Y1P.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_9_1_X3A.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_33_1_HWB.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_8_1_bXz.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_31_1_vbA.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_19_1_pJk.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_44_1_2v3.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_50_HT_100_7TeV-madgraph/ttbsm_ultraslim_46_1_AaF.root",
])