import FWCore.ParameterSet.Config as cms

maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )
readFiles = cms.untracked.vstring()
secFiles = cms.untracked.vstring() 
source = cms.Source ("PoolSource",fileNames = readFiles, secondaryFileNames = secFiles)
readFiles.extend( [
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_10_1_wnW.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_11_1_GuV.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_1_1_E3F.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_12_1_f0V.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_13_1_nlz.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_14_1_o8e.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_15_1_4qo.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_16_1_v03.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_17_1_cd6.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_18_1_r18.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_19_1_5Gj.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_20_1_kaI.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_21_1_GPw.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_2_1_Kqi.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_22_1_8eG.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_23_1_ZDQ.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_24_1_Fmy.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_25_1_qeP.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_26_1_Wkx.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_27_1_Zxs.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_28_1_03T.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_29_1_MMK.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_30_1_Urx.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_31_1_If5.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_3_1_bnf.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_32_1_RsW.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_33_1_mHz.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_34_1_8Nc.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_35_1_uB6.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_36_1_pHS.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_37_1_eoF.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_38_1_1Mh.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_39_1_6I1.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_40_1_4hJ.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_41_1_Axm.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_4_1_XC6.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_42_1_j7h.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_43_1_6ag.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_44_1_kCh.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_45_1_4dw.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_46_1_Ia6.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_47_1_u0r.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_48_1_zH6.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_49_1_faa.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_50_1_35P.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_51_1_GDE.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_5_1_RaK.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_6_1_ho0.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_7_1_zoq.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_8_1_E6x.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_9_1_hpD.root"
])
