import FWCore.ParameterSet.Config as cms

maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )
readFiles = cms.untracked.vstring()
secFiles = cms.untracked.vstring() 
source = cms.Source ("PoolSource",fileNames = readFiles, secondaryFileNames = secFiles)
readFiles.extend( [
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_44_1_cpi.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_20_1_SGt.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_33_1_A5P.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_2_1_blr.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_48_1_coV.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_46_1_Maz.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_43_1_Cnk.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_38_1_AHW.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_24_1_z34.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_36_1_RlI.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_27_1_XKK.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_18_1_n6J.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_26_1_kHd.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_15_1_lxp.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_32_1_JQu.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_13_1_2WB.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_10_1_wAn.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_47_1_lt5.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_28_1_O4d.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_7_1_WAe.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_45_1_GL1.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_29_1_Rcx.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_9_1_FsK.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_41_1_fR1.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_31_1_Y2S.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_50_1_VYU.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_42_1_YJ9.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_17_1_DhD.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_6_1_yXd.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_39_1_1zi.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_30_1_uqd.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_51_1_xQx.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_22_1_gAe.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_34_1_8J5.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_14_1_dKN.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_49_1_fN9.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_21_1_ddv.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_11_1_B8w.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_37_1_fQs.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_12_1_vSG.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_16_1_mUb.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_25_1_F4b.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_19_1_k8P.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_3_1_cTD.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_1_1_kUO.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_40_1_glU.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_5_1_5Zy.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_35_1_Zui.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_4_1_mxF.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_8_1_z0L.root",
"dcap:///pnfs/cms/WAX/resilient/csilkw2/StopSearches/ZJetsToNuNu_100_HT_200_7TeV-madgraph/ttbsm_ultraslim_23_1_jl1.root",
])